# Generated by Django 2.0.4 on 2018-05-01 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='word',
            name='definition',
        ),
        migrations.AddField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Word'),
        ),
    ]
